/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ftdca;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author Mehedi Hasan
 */
public class RegistrationForm extends javax.swing.JFrame {
    //for database
    Connection cn=null;
    Statement stmt=null;
    ResultSet res=null;
    String driver="com.mysql.jdbc.Driver";
    String url="jdbc:mysql://localhost:3306/ftdca";
    
     //Credentials
    private static String Email, Password;  //user
    private static String ConsumerKey, ConsumerKeySecret, AccessToken, AccessTokenSecret; //Twitter
    private static String AppId, AppSecret; //Facebook
    
    
    /**
     * Creates new form RegistrationForm
     */
    public RegistrationForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RequestLabel = new javax.swing.JLabel();
        EmailLabel = new javax.swing.JLabel();
        EmailField = new javax.swing.JTextField();
        PasswordLabel = new javax.swing.JLabel();
        PassowrdField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        ConsumerKeyField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        ConsumerKeySecretField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        AccessTokenField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        AccessTokenSecretField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        AppIdField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        AppSecretField = new javax.swing.JTextField();
        RegisterButton = new javax.swing.JButton();
        TwitterCredentialAskingLabel = new javax.swing.JLabel();
        FacebookCredentialAskingLabel = new javax.swing.JLabel();
        BackButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(3840, 2160));
        setMinimumSize(new java.awt.Dimension(1200, 700));

        RequestLabel.setFont(new java.awt.Font("Lucida Calligraphy", 0, 18)); // NOI18N
        RequestLabel.setText("Enter The Required Information");

        EmailLabel.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        EmailLabel.setText("Enter Email");

        PasswordLabel.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        PasswordLabel.setText("Enter Password");

        jLabel1.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        jLabel1.setText("Enter ConsumerKey");

        jLabel2.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        jLabel2.setText("Enter ConsumerKeySecret");

        jLabel3.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        jLabel3.setText("Enter AccessTokenSecret");

        jLabel4.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        jLabel4.setText("Enter AccessToken");

        jLabel5.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        jLabel5.setText("Enter AppId");

        jLabel6.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        jLabel6.setText("Enter AppSecret");

        RegisterButton.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        RegisterButton.setText("Register");
        RegisterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterButtonActionPerformed(evt);
            }
        });

        TwitterCredentialAskingLabel.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        TwitterCredentialAskingLabel.setText("Enter Following Credential For Twitter");

        FacebookCredentialAskingLabel.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        FacebookCredentialAskingLabel.setText("Enter Following Credential For FB");

        BackButton.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        BackButton.setText("Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EmailLabel)
                    .addComponent(PasswordLabel)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4))
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PassowrdField)
                    .addComponent(ConsumerKeyField)
                    .addComponent(ConsumerKeySecretField)
                    .addComponent(AccessTokenField)
                    .addComponent(AccessTokenSecretField)
                    .addComponent(AppIdField)
                    .addComponent(AppSecretField)
                    .addComponent(EmailField, javax.swing.GroupLayout.PREFERRED_SIZE, 723, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(166, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(FacebookCredentialAskingLabel)
                        .addGap(429, 429, 429))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(TwitterCredentialAskingLabel)
                        .addGap(393, 393, 393))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(RequestLabel)
                        .addGap(385, 385, 385))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(RegisterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(104, 104, 104)
                        .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(302, 302, 302))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(RequestLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmailLabel)
                    .addComponent(EmailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PasswordLabel)
                    .addComponent(PassowrdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TwitterCredentialAskingLabel)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(ConsumerKeyField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ConsumerKeySecretField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(43, 43, 43)
                        .addComponent(AccessTokenField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AccessTokenSecretField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(26, 26, 26)
                .addComponent(FacebookCredentialAskingLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AppIdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AppSecretField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RegisterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(139, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegisterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterButtonActionPerformed
        Email = EmailField.getText();
        Password = PassowrdField.getText();
        
        ConsumerKey = ConsumerKeyField.getText();
        ConsumerKeySecret = ConsumerKeySecretField.getText();
        AccessToken = AccessTokenField.getText();
        AccessTokenSecret = AccessTokenSecretField.getText();
        
        AppId = AppIdField.getText();
        AppSecret = AppSecretField.getText();
        //validating if they are empty or not
        if(Email.isEmpty() || Password.isEmpty() || ConsumerKey.isEmpty() || ConsumerKeySecret.isEmpty() || AccessToken.isEmpty() || AccessTokenSecret.isEmpty() || AppId.isEmpty() || AppSecret.isEmpty()){
            JOptionPane.showMessageDialog(null, "All Fields Are Required!!!");
        } else{
            //trying to register into database
            try{
                //creating a connection
                cn = DriverManager.getConnection(url,"root","");         
                //create statement
                stmt=cn.createStatement();
                
                String TableStructure = "CREATE TABLE IF NOT EXISTS `registration` (`Serial` int(10) NOT NULL AUTO_INCREMENT, `Email` varchar(255) NOT NULL,  `Password` varchar(255) NOT NULL,  `ConsumerKey` varchar(255) NOT NULL,  `ConsumerKeySecret` varchar(255) NOT NULL,  `AccessToken` varchar(255) NOT NULL,  `AccessTokenSecret` varchar(255) NOT NULL,  `AppId` varchar(255) NOT NULL,  `AppSecret` varchar(255) NOT NULL,  PRIMARY KEY (`Serial`),  UNIQUE KEY `Email` (`Email`)) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=3 ;";
                String query="INSERT INTO `ftdca`.`registration` (`Serial`, `Email`, `Password`, `ConsumerKey`, `ConsumerKeySecret`, `AccessToken`, `AccessTokenSecret`, `AppId`, `AppSecret`) VALUES (NULL, '"+Email+"', '"+Password+"', '"+ConsumerKey+"', '"+ConsumerKeySecret+"', '"+AccessToken+"', '"+AccessTokenSecret+"', '"+AppId+"', '"+AppSecret+"');";
                
                if(stmt.execute(TableStructure) == false){
                    if(stmt.execute(query) == false){
                    //System.out.println("Success");
                    //setting this window Invisible
                    this.setVisible(false);
                    //Login
                    Login l = new Login();
                    l.setVisible(true);  
                    } else {
                        JOptionPane.showMessageDialog(null, "Can't insert");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Error occured while creating table");
                }
            } catch(Exception ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_RegisterButtonActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        Login login = new Login();
        this.setVisible(false);
        login.setVisible(true);
    }//GEN-LAST:event_BackButtonActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AccessTokenField;
    private javax.swing.JTextField AccessTokenSecretField;
    private javax.swing.JTextField AppIdField;
    private javax.swing.JTextField AppSecretField;
    private javax.swing.JButton BackButton;
    private javax.swing.JTextField ConsumerKeyField;
    private javax.swing.JTextField ConsumerKeySecretField;
    private javax.swing.JTextField EmailField;
    private javax.swing.JLabel EmailLabel;
    private javax.swing.JLabel FacebookCredentialAskingLabel;
    private javax.swing.JTextField PassowrdField;
    private javax.swing.JLabel PasswordLabel;
    private javax.swing.JButton RegisterButton;
    private javax.swing.JLabel RequestLabel;
    private javax.swing.JLabel TwitterCredentialAskingLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
